### PR TITLE
Fix issue #208: Enable scroll when menu is open and close menu on scroll

### LINKED ISSUE #208: Scroll freezes when menu is open on mobile
### Issue
Upon clicking hamburger menu on mobile (Chrome/Safari), the Menu shows up but does not go away. This is fine because the user may want to click on something. But when you begin scrolling, it still does not go away and the scroll does not work.  

image

### Workaround
Only when tapping on any empty area of screen does it go away. 

### Expected Outcome
When scrolling begins, menu should go away and scrolling should continue

### PR DESCRIPTION
**Pull request by souad988**
## Summary
Anable scrolling when profile menu is open.   
Add scroll trigger to close menu when scrolling begins.
Closes #208,

## Changes

- Add  disableScrollLock={true} property to Menu.
- Add useEffect to closeProfileMenu when scroll triggered 

## Screenshots

scroll anabled

### CODE REVIEW

**Comment by tuxology** [comment]
Thanks @souad988 We are reviewing this one :+1:

File: zubhub_frontend/zubhub/src/views/PageWrapper.jsx [hunk 1]
```diff
@@ -159,6 +164,9 @@ function PageWrapper(props) {
               >
                 <TranslateIcon />
                 <Select
+                  menuProps={{
```
Comment (NdibeRaymond) [inline zubhub_frontend/zubhub/src/views/PageWrapper.jsx]: like you said this doesn't work here, so perhaps we should remove it from here?

**Review by NdibeRaymond — CHANGES_REQUESTED** [review]

**Comment by NdibeRaymond** [comment]
like I said in the previous PR that was closed, you should add disableScrollLock true to Comment.jsx line 126 and Profile.jsx line 139

File: zubhub_frontend/zubhub/src/views/PageWrapper.jsx (hunk 1 above)
Comment (souad988) [reply zubhub_frontend/zubhub/src/views/PageWrapper.jsx]: yes i kept it just in case i'm missing something but now i removed it

**Comment by souad988** [comment]
> like I said in the previous PR that was closed, you should add disableScrollLock true to Comment.jsx line 126 and Profile.jsx line 139

thanks for specifying , done

**Comment by souad988** [comment]
> Thanks @souad988 We are reviewing this one 👍

thanks @tuxology  for leting me know 😊

**Review by NdibeRaymond — APPROVED** [review]
