### PR TITLE
(enhancement) Update activities feature flow

### LINKED ISSUE #863: Staff should be able to delete an activity
**Describe the bug**
Deleting an activity doesn't work

**To Reproduce**

1. Go to 'https://zubhub.unstructured.studio/'
2. Click on 'Create Activity' from sidebar
3. Try to create an activity: 'https://zubhub.unstructured.studio/activities/create'
4. Only users with staff privileges are able to see activities here https://zubhub.unstructured.studio/activities
5. Click an activity. You will see an option to edit, and delete by clicking on three dots from the top right.
6. Click on the delete option

**Expected behavior**
When you click on delete, the activity should be deleted

### PR DESCRIPTION
**Pull request by coderatomy**
## Summary
fixes #863, #913, #898
In general, this specifically enhances the Activities feature flow by adding UIs to the `/activities/my-activities`, `/activities/un-published`,  `/activities/:id/edit`, plus activity deletion

## Changes
- Adds `MyActivities` component
- Adds support for editting, unplishing and publishing an activity
- Refactors the activity editting flow
- Adds route protection to activities
- Updated validation for activity forms

## Notes
All routes associated with activities have been implemented, each with its corresponding user interfaces. However, it's worth noting that the complete workflow for activities, including where users can find options for creating activities, wasn't entirely clear initially. Despite this, all routes have been established. The remaining task is to properly connect the actions to their respective routes, and once done, the feature will be seamlessly integrated.
cc @tuxology @yokwejuste @rak16 

## Screenshots
image
image
image
[Screencast from 2023-10-13 05-57-02.webm](https://github.com/unstructuredstudio/zubhub/assets/141822315/7daf3a37-2a9e-4bce-b8fa-54271ce8c55d)

### CODE REVIEW

File: zubhub_frontend/zubhub/src/api/api.js [hunk 1]
```diff
@@ -762,18 +726,7 @@ class API {
...
-    title,
-    description,
-    video,
-    images,
-    materials_used,
-    category,
-    tags,
-    publish,
-  }) => {
+  updateProject = ({ token, id, title, description, video, images, materials_used, category, tags, publish }) => {
```
Comment (rak16) [inline zubhub_frontend/zubhub/src/api/api.js:732]: Why are we reformatting this?

File: zubhub_frontend/zubhub/src/api/api.js [hunk 2]
```diff
@@ -859,11 +810,11 @@ class API {
   };
 
   /**
-  * @method getActivity
-  * @author Yaya Mamoudou <yayamamoudou0@gmail.com>
-  *
-  * @todo - describe method's signature
-  */
+   * @method getActivity
```
Comment (rak16) [inline zubhub_frontend/zubhub/src/api/api.js:816]: Why are we adding spaces here?

Comment (rak16) [reply zubhub_frontend/zubhub/src/api/api.js:816]: I think we should stick to the formatting convention being followed in the code for now instead of adding new linting rules. Changes like these could inflate the PR and make it difficult to review the actual logical changes. 

That said, we can discuss and establish linting rules and eventually add eslint to the project so that everyone has the same formatting standards.

File: zubhub_frontend/zubhub/src/components/activity/activity.jsx [hunk 3]
```diff
@@ -34,6 +30,8 @@ const useCommonStyles = makeStyles(commonStyles);
 const useStyles = makeStyles(style);
 function Activity(props) {
   const { activity, t } = { ...props };
+
+  console.log(props, 'rjtjtjtttttt');
```
Comment (rak16) [inline zubhub_frontend/zubhub/src/components/activity/activity.jsx]: Remove log

File: zubhub_frontend/zubhub/src/views/activity_details/ActivityDetailsV2.jsx [hunk 4]
```diff
@@ -41,6 +41,7 @@ export default function ActivityDetailsV2(props) {
   const classes = makeStyles(activityDefailsStyles)();
   const commonClasses = makeStyles(styles)();
 
+  // console.log(activity, 'ACTIVITY');
```
Comment (rak16) [inline zubhub_frontend/zubhub/src/views/activity_details/ActivityDetailsV2.jsx]: Remove this too

File: zubhub_frontend/zubhub/src/views/my_activities/MyActivities.jsx [hunk 5]
```diff
@@ -0,0 +1,113 @@
...
+import styles from '../../assets/js/styles/views/activities/activitiesStyles';
+import { makeStyles } from '@material-ui/core/styles';
+import ErrorPage from '../error/ErrorPage';
+import DefaultStyles from '../../assets/js/styles';
+import { Grid, Box, Typography } from '@material-ui/core';
+import LoadingPage from '../loading/LoadingPage';
+const useStyles = makeStyles(styles);
+
+function MyActivities(props) {
+  console.log(props, 'PROPSSSSS');
```
Comment (rak16) [inline zubhub_frontend/zubhub/src/views/my_activities/MyActivities.jsx]: Remove log

File: zubhub_frontend/zubhub/src/api/api.js [hunk 6]
```diff
@@ -1144,12 +1090,12 @@ class API {
   };
 
   getUnPublishedActivities = token => {
-    const url = 'activities/unPublished';
+    const url = 'activities/un-published';
```
Comment (rak16) [inline zubhub_frontend/zubhub/src/api/api.js:1095]: This should be changed to `unpublished`. Refer to your change in the backend

**Comment by rak16** [comment]
I skimmed through the changes. Haven't looked at the net-new changes because the PR looked too bloated. It'd be great if we could just check-in the logical changes and take care of the formatting separately, as suggested.

**Review by rak16 — CHANGES_REQUESTED** [review]

File: zubhub_frontend/zubhub/src/api/api.js (hunk 2 above)
Comment (brrkrmn) [reply zubhub_frontend/zubhub/src/api/api.js:816]: Until then, @coderatomy you can use 'save without formatting' option in vscode to avoid changing the lines you haven't touched

**Comment by coderatomy** [comment]
Note:  This is a draft @rak16  and @brrkrmn. Never marked ready for review yet

**Comment by coderatomy** [comment]
> I skimmed through the changes. Haven't looked at the net-new changes because the PR looked too bloated. It'd be great if we could just check-in the logical changes and take care of the formatting separately, as suggested.

I always direct where changes are when my PRs are ready for review. I make work easier for you reviewers.
Concerning `eslint` and `prettier`, am working on that and I recall presenting this to the community sometime back. Pushing a fix soon

File: zubhub_frontend/zubhub/src/api/api.js (hunk 2 above)
Comment (coderatomy) [reply zubhub_frontend/zubhub/src/api/api.js:816]: > Until then, @coderatomy you can use 'save without formatting' option in vscode to avoid changing the lines you haven't touched

The project currently utilizes a Prettier configuration specified in the .prettierrc.yaml file. However, the existing configuration might not be comprehensive or optimal. If we consistently adhere to this configuration, it would mitigate problems associated with incorrect code linting and formatting. Failure to activate the `format on save` feature bring up such issues, allowing improperly formatted code to persist.
Just a clarification @brrkrmn, every file here has a change. That's why I had to save

**Comment by rak16** [comment]
> Note: This is a draft @rak16 and @brrkrmn. Never marked ready for review yet

Hey, the whole reason for a draft PR is to gather early feedback. In case you are not looking for feedback, you might as well not raise a PR.

**Comment by rak16** [comment]
> > I skimmed through the changes. Haven't looked at the net-new changes because the PR looked too bloated. It'd be great if we could just check-in the logical changes and take care of the formatting separately, as suggested.
> 
> I always direct where changes are when my PRs are ready for review. I make work easier for you reviewers. Concerning `eslint` and `prettier`, am working on that and I recall presenting this to the community sometime back. Pushing a fix soon

I see. In that case, let's raise an issue and work on this once we have a consensus. There are multiple  style guides  available which we can choose from. Let's avoid adding our own rules until then. Thanks.

**Comment by coderatomy** [comment]
> I see. In that case, let's raise an issue and work on this once we have a consensus. There are multiple style guides available which we can choose from. Let's avoid adding our own rules until then. Thanks.

Alright then. Though I have that work in progress. Be ready for your review. Thanks
But I believe this can work for now. Since nothing will change, or  break. Am actually following the [**.prettierrc.yaml**](https://github.com/unstructuredstudio/zubhub/blob/master/zubhub_frontend/zubhub/.prettierrc.yaml#L1C1-L10C21). You can check it out

**Comment by rak16** [comment]
Okay, but as per what I feel and also what @tuxology veritably suggested [here](https://unstructured.zulipchat.com/#narrow/stream/246561-ZubHub/topic/Welcome.20.26.20introductions/near/396391551), we can skip the linting hassles for now. Let's listen to the mentors. They know what they are talking about :)

In case you feel really strongly about it, please move it to a separate PR.

File: zubhub_frontend/zubhub/src/views/create_activity/CreateEditActivity.jsx [hunk 7]
```diff
@@ -102,45 +104,40 @@ export default function CreateActivity(props) {
...
   const previous = () => go('prev');
-  const next = async () => {
-    let error = await checkErrors();
 
-    console.log(error);
-    if (Object.keys(error || {}).length > 0) return;
+  const submit = async publish => {
+    const errors = await checkErrors().then(errors => errors);
+
+    if (Object.keys(errors).length > 0) {
```
Comment (coderatomy) [inline zubhub_frontend/zubhub/src/views/create_activity/CreateEditActivity.jsx:112]: breaking function execution if the're any validation errors

File: zubhub_frontend/zubhub/src/views/activities/activities.jsx [hunk 8]
```diff
@@ -24,35 +24,40 @@ function Activities(props) {
...
   const { activities } = useSelector(state => state);
-  let [activityList, setActivityList] = useState([]);
+  const [activityList, setActivityList] = useState(props?.activities ?? []);
 
   const commonClasses = makeStyles(DefaultStyles)();
 
-  useEffect(() => {
-    setActivityList(activities.all_activities);
-  }, [activities]);
+  const flagMap = useMemo(
```
Comment (coderatomy) [inline zubhub_frontend/zubhub/src/views/activities/activities.jsx:30]: memoizing the flagMap

File: zubhub_frontend/zubhub/src/views/activities/activities.jsx [hunk 9]
```diff
@@ -24,35 +24,40 @@ function Activities(props) {
...
-    } else {
-      await props.getActivities(props.t);
+  useEffect(() => {
+    async function fetcher() {
+      setLoading(true);
+      if (location.state?.flag && flagMap[location.state.flag]) {
+        await flagMap[location.state.flag]();
+      } else {
+        await props.getActivities(props.t);
+        await props.getMyActivities(props.auth);
```
Comment (coderatomy) [inline zubhub_frontend/zubhub/src/views/activities/activities.jsx]: adding `myActivities` to `allActivities`  such that a user can see personally created routes on `/activities`.

File: zubhub_frontend/zubhub/src/views/activity_details/ActivityDetailsV2.jsx [hunk 10]
```diff
@@ -260,22 +260,18 @@ export default function ActivityDetailsV2(props) {
...
-                activity={activity}
-                key={activity.id}
-                t={t}
-                // updateProjects={res => handleSetState(updateProjects(res, state, props, toast))}
-                {...props}
-              />
-            </Grid>
-          ))}
+          {moreActivities
+            .filter(({ id }) => id !== props.match.params.id)
```
Comment (coderatomy) [inline zubhub_frontend/zubhub/src/views/activity_details/ActivityDetailsV2.jsx:285]: simple change such that the currently browsed activity doesn't show up in the `moreActivities` section

File: zubhub_frontend/zubhub/src/views/create_activity/CreateEditActivity.jsx [hunk 11]
```diff
@@ -42,7 +43,8 @@ const steps = ['Activity Basics', 'Activity Details'];
 
 let firstRender = true;
 
-export default function CreateActivity(props) {
+function CreateEditActivity(props) {
+  const editting = props?.editting;
```
Comment (coderatomy) [inline zubhub_frontend/zubhub/src/views/create_activity/CreateEditActivity.jsx:48]: added an `editting` property to handle data editting and change in words titles, button labels.

File: zubhub_frontend/zubhub/src/views/create_activity/CreateEditActivity.jsx [hunk 12]
```diff
@@ -102,45 +104,40 @@ export default function CreateActivity(props) {
...
-    }
-
-    if (activeStep === 2) {
-      return formikStep2.setTouched({ introduction: true }, true);
-    }
+    return formikStep2.setTouched({ introduction: true }, true);
   };
 
-  const go = direction => {
+  const go = async direction => {
```
Comment (coderatomy) [inline zubhub_frontend/zubhub/src/views/create_activity/CreateEditActivity.jsx:136]: refactored the `go` function such that it first checks for validation errors before going to the next step

File: zubhub_frontend/zubhub/src/views/create_activity/CreateEditActivity.jsx [hunk 13]
```diff
@@ -158,23 +155,37 @@ export default function CreateActivity(props) {
...
-        ) : (
-          <Typography style={{ fontWeight: '600' }}>{index + 1}</Typography>
-        )}
-      </Box>
-      <Typography className={clsx(classes.stepLabel, (isActive(index) || isCompleted(index)) && classes.activeLabel)}>
-        {label}
-      </Typography>
-    </Box>
-  ));
+  const renderSteps = useMemo(
```
Comment (coderatomy) [inline zubhub_frontend/zubhub/src/views/create_activity/CreateEditActivity.jsx:159]: memoized the `renderSteps`

File: zubhub_frontend/zubhub/src/views/create_activity/CreateEditActivity.jsx [hunk 14]
```diff
@@ -229,18 +242,30 @@ export default function CreateActivity(props) {
               Previous
             </CustomButton>
           )}
-
+          {activeStep === 2 && (
```
Comment (coderatomy) [inline zubhub_frontend/zubhub/src/views/create_activity/CreateEditActivity.jsx]: Thought it is ideally nice to have drafting and publishing abilities differently. This button sets the activity as a draft by just making `publish: false`. 
Still open for suggestions @tuxology

File: zubhub_frontend/zubhub/src/views/create_activity/script.js [hunk 15]
```diff
@@ -10,787 +10,722 @@ const idPrefix = 'activitystep';
...
 
-    const activityId = props.match.params?.id
-    let createOrUpdateResponse;
+  const activityId = props.match.params?.id;
+  let createOrUpdateResponse;
 
-    if (props.match.params.id) {
-        // API call to the update activity
-        createOrUpdateResponse = await API.updateActivity(props.auth.token, activityId, formData)
+  if (activityId) {
```
Comment (coderatomy) [inline zubhub_frontend/zubhub/src/views/create_activity/script.js:656]: performs activity data updating and creation.

Since we have access to the activity `id` in the `url` when editting, we aim on that as the source of truth. So if the `id` is available, we call `updateActivity` else `createActivity`.
Then according to the different response statuses, we show the `toasts`

File: zubhub_frontend/zubhub/src/views/my_activities/MyActivities.jsx [hunk 16]
```diff
@@ -0,0 +1,111 @@
...
+import Activity from '../../components/activity/activity';
+import styles from '../../assets/js/styles/views/activities/activitiesStyles';
+import { makeStyles } from '@material-ui/core/styles';
+import ErrorPage from '../error/ErrorPage';
+import DefaultStyles from '../../assets/js/styles';
+import { Grid, Box, Typography } from '@material-ui/core';
+import LoadingPage from '../loading/LoadingPage';
+const useStyles = makeStyles(styles);
+
+function MyActivities(props) {
```
Comment (coderatomy) [inline zubhub_frontend/zubhub/src/views/my_activities/MyActivities.jsx:21]: This get's loaded at `activities/my-activities` and generally shows user specific published activities.

**Comment by tuxology** [comment]
@coderatomy Before I begin reviewing this, a few points that I need clarification on:

Initial intention of activities feature is as follows:
 - Logged in Users: Can browse activities, cannot create/edit activities
 - Non logged in Users: are redirected to login
 - Logged in users with Staff role: Can create activities in UI - they get a Create Activity link on sidebar and can continue to create activity, can publish/unpublish ANY activity on platform. 
 - The publish, unpublish button was added because we wanted another role - Educator to be allowed to create activities - which do not get published immediately. These activities are only visible to Staff roles who can publish/unpublish. Is the button added to publish/unpublish 

Are the above constraints fulfilled? 

In addition, a few more points about the design: 
 - We don not have a clear design yet on the activities list view (`/activities` page) as well as Activities card view. In absence of this, just ensure that we have at least proper padding between each card and with the sidebar. 
 - Publish/unpublish button can be added in the Edit and delete settings icon.

**Comment by coderatomy** [comment]
**Logged in Users: Can browse activities, cannot create/edit activities**
   Well here we protected the links and forgot the routes, according to [here](https://github.com/unstructuredstudio/zubhub/blob/master/zubhub_frontend/zubhub/src/components/hamburger_menu/HamburgerMenu.jsx#L88C1-L130C9). I just added `/activities/create` in the url and was able to create one. Perhaps we need an improvement there according to what you said.

**Non logged in Users: are redirected to login**
   I just see the `404`. No redirection

**Logged in users with Staff role...**
Earlier, I thought anyone on Zubhub can create an account since I could. Thanks for the clarity. That's why I actually made `myActivities`  be viewed on `/activities` together with `allActivities`. 
The only thing am not sure of is when, where and how these flags are given to users. I only see where we are persisting it onto the history stack yet at the same time that link is protected to only users with those flags. Currently, I only see support for `creators` tag. Perhaps you have more context on this @tuxology?

**The publish, unpublish button**
I see support for publish/unpublish through the publish boolean, but not in the UI, not any button. I think I can add that. 


So briefly that's all. The few changes I have to revert are concerning how activities should be viewed The rest are still valid improvements. Just a few key notes;
- Would you like a redirection to the login for unauthenticated users?
- Should we add route protection to `/activities/create` and `activities/:id/edit` for users without Staff privileges?
- The only question that still stands. How are these roles given to users?

Thanks alot @tuxology

**Comment by tuxology** [comment]
@coderatomy Some more details and clarifications:

> Well here we protected the links and forgot the routes, according to [here](https://github.com/unstructuredstudio/zubhub/blob/master/zubhub_frontend/zubhub/src/components/hamburger_menu/HamburgerMenu.jsx#L88C1-L130C9). I just added /activities/create in the url and was able to create one. Perhaps we need an improvement there according to what you said.

Yes. We need to update this as per requirements

> Non logged in Users: are redirected to login
> I just see the 404. No redirection

I recall we did route protection. Ideally we should finalize design for login redirection before doing this. For now, you can redirect to just login like you did for route protection IIRC.

> The only thing am not sure of is when, where and how these flags are given to users. I only see where we are persisting it onto the history stack yet at the same time that link is protected to only users with those flags. Currently, I only see support for creators tag. Perhaps you have more context on this @tuxology?

These tags can be set from the Django Admin under Creator -> Tag.

> I see support for publish/unpublish through the publish boolean, but not in the UI, not any button. I think I can add that.

Can you add this button under the Edit/Delete option in the three dots menu. Note that Publish/unpublish is only relevant and visible for Staff users on ALL projects irrespective of who created them. 

> Would you like a redirection to the login for unauthenticated users?

Yes, we can do it for now, but this needs to be eventually done properly when best parts of #802 is done. 

> Should we add route protection to /activities/create and activities/:id/edit for users without Staff privileges?

Yes. Redirect them to login and nothing more

File: zubhub_frontend/zubhub/src/api/api.js [hunk 17]
```diff
@@ -827,9 +780,7 @@ class API {
     const method = 'PATCH';
     const body = JSON.stringify({});
     return this.request({ url, method, token, body }).then(res =>
-      Promise.resolve(
-        res.status === 200 ? res.json() : { details: 'unknown error' },
-      ),
+      Promise.resolve(res.status === 200 ? res.json() : { details: 'unknown error' }),
```
Comment (yokwejuste) [inline zubhub_frontend/zubhub/src/api/api.js:786]: @coderatomy  what error can happen here if not of wrong authentication ?

File: zubhub_frontend/zubhub/src/views/activities/activities.jsx (hunk 9 above)
Comment (yokwejuste) [reply zubhub_frontend/zubhub/src/views/activities/activities.jsx]: where are you proving the restriction to creators to this content?

File: zubhub_frontend/zubhub/src/views/create_activity/script.js [hunk 18]
```diff
@@ -10,787 +10,722 @@ const idPrefix = 'activitystep';
...
-        media_upload: {
-            upload_dialog: false,
-            images_to_upload: [],
-            videos_to_upload: [],
-            upload_info: {},
-            upload_percent: 0,
-            uploaded_images_url: [],
-            uploaded_videos_url: [],
-        },
+  image_field_touched: false,
```
Comment (yokwejuste) [inline zubhub_frontend/zubhub/src/views/create_activity/script.js:20]: hey @coderatomy to make it easy, separate the linting and formatting from the changes.

**Review by yokwejuste — COMMENTED** [review]
Here is something to have a look at.

@tuxology I think this PR has a lot of features and will be good to be reviewed to free up some pending issues.

:) Great job @coderatomy

File: zubhub_frontend/zubhub/src/views/activities/activities.jsx (hunk 9 above)
Comment (coderatomy) [reply zubhub_frontend/zubhub/src/views/activities/activities.jsx]: Everything is documented in the description and the comments here so far. Surely, if you read through, you will get the context of what's going on. Check @tuxology's comment. Am reverting this

**Comment by coderatomy** [comment]
Concerning redirections @tuxology, let me wait for my PR here https://github.com/unstructuredstudio/zubhub/pull/825 to be merged in and I do an update

**Comment by tuxology** [comment]
OK, so I am inclined to first merge #825 now. I think we need to discuss #918 a bit more hence this will unblock you first. I was expecting both of these to be unified eventually - since they are related

**Comment by yokwejuste** [comment]
> OK, so I am inclined to first merge #825 now. I think we need to discuss #918 a bit more hence this will unblock you first. I was expecting both of these to be unified eventually - since they are related

I think @coderatomy has to fix the conflicts here to keep this PR in the stack and make it valid

File: zubhub_frontend/zubhub/src/App.js [hunk 19]
```diff
@@ -457,32 +448,12 @@ function App(props) {
...
-                <LazyImport LazyComponent={Activities} {...routeProps} {...props} />
-              </PageWrapper>
-            )}
-          />
+          <ProtectedRoute path="/activities/create" component={CreateEditActivity} {...props} />
+          <ProtectedRoute path="/activities/my-activities" component={MyActivities} {...props} />
+          <ProtectedRoute path="/activities/:id/linked-projects" component={LinkedProjects} {...props} />
+          <ProtectedRoute path="/activities/:id/edit" component={CreateEditActivity} {...props} />
+          <ProtectedRoute path="/activities/:id" component={ActivityDetails} {...props} />
+          <ProtectedRoute path="/activities" component={Activities} {...props} />
```
Comment (coderatomy) [inline zubhub_frontend/zubhub/src/App.js:456]: Protecting all routes related to `/activities`

File: zubhub_frontend/zubhub/src/components/form/dropdown/Dropdown.jsx [hunk 20]
```diff
@@ -79,7 +79,7 @@ export default function Dropdown({
       </label>
 
       {helperText && (
-        <Typography className={commonClasses.textSmall} style={{ marginBottom: 10 }}>
+        <Typography color={error ? 'error' : ''} className={commonClasses.textSmall} style={{ marginBottom: 10 }}>
```
Comment (coderatomy) [inline zubhub_frontend/zubhub/src/components/form/dropdown/Dropdown.jsx:82]: Changing helper text fill color once the're validation errors

File: zubhub_frontend/zubhub/src/views/create_activity/script.js [hunk 21]
```diff
@@ -10,787 +10,723 @@ const idPrefix = 'activitystep';
...
-        .of(
-            Yup.object().shape({
-                name: Yup.string().required('Name is required')
-            })
-        ),
+  title: Yup.string().max(100, 'max').required('required'),
+  class_grade: Yup.object().shape({ name: Yup.string() }).required('Select a grade'),
+  category: Yup.array().of(Yup.object().shape({
+    name: Yup.string().required()
+  })).required('A category is required')
```
Comment (coderatomy) [inline zubhub_frontend/zubhub/src/views/create_activity/script.js:439]: Added validation for all step 1 fields. Made all of them required

File: zubhub_frontend/zubhub/src/views/create_activity/script.js [hunk 22]
```diff
@@ -10,787 +10,723 @@ const idPrefix = 'activitystep';
...
-    materials_used: Yup.string(),
-    images: Yup.array(),
-    making_steps: Yup.array().of(Yup.object().shape({
-        title: Yup.string(),
-        description: Yup.string().required(),
-        step_order: Yup.number(),
-        images: Yup.array(),
-        materials_used_image: Yup.array()
-    }))
+  introduction: Yup.string().max(1000, 'max').required('Add an introduction'),
```
Comment (coderatomy) [inline zubhub_frontend/zubhub/src/views/create_activity/script.js:452]: Added validation for all step 2 fields. Made all of them required

File: zubhub_frontend/zubhub/src/views/create_activity/CreateEditActivity.jsx [hunk 23]
```diff
@@ -203,7 +214,9 @@ export default function CreateActivity(props) {
       <Box className={classes.formContainer}>
         <Grid item md={12} lg={12}>
           <Box sx={{ textAlign: isSmallScreen ? 'left' : 'center' }}>
-            <Typography className={clsx(commonClasses.title1)}>Create Activity</Typography>
+            <Typography className={clsx(commonClasses.title1)}>
+              {editting ? 'Edit Activity' : 'Create Activity'}
```
Comment (yokwejuste) [inline zubhub_frontend/zubhub/src/views/create_activity/CreateEditActivity.jsx:219]: can we have translation implemented here?

File: zubhub_frontend/zubhub/src/views/create_activity/script.js [hunk 24]
```diff
@@ -10,787 +10,723 @@ const idPrefix = 'activitystep';
...
+  images: Yup.array().required('Add the activity image'),
+  making_steps: Yup.array().of(
+    Yup.object().shape({
+      title: Yup.string(),
+      description: Yup.string().required(),
+      step_order: Yup.number(),
+      images: Yup.array(),
+      materials_used_image: Yup.array(),
+    }),
+  ).required('Atleast one step is required'),
```
Comment (yokwejuste) [inline zubhub_frontend/zubhub/src/views/create_activity/script.js:466]: For all these errors displayed we need translations here

**Review by yokwejuste — COMMENTED** [review]
Just some little point calling my attention and also the linting and formatting make the review take more time

File: zubhub_frontend/zubhub/src/views/create_activity/CreateEditActivity.jsx (hunk 23 above)
Comment (coderatomy) [reply zubhub_frontend/zubhub/src/views/create_activity/CreateEditActivity.jsx:219]: On it. Thanks

File: zubhub_frontend/zubhub/src/views/activity_details/ActivityDetailsV2.jsx [hunk 25]
```diff
@@ -81,6 +82,18 @@ export default function ActivityDetailsV2(props) {
     props.history.push(`${props.location.pathname}/edit`);
   };
 
+  const handleUpublishAndPublish = async () => {
```
Comment (coderatomy) [inline zubhub_frontend/zubhub/src/views/activity_details/ActivityDetailsV2.jsx:85]: handles the publishing and unpublishing of activities

File: zubhub_frontend/zubhub/src/views/activity_details/ActivityDetailsV2.jsx [hunk 26]
```diff
@@ -135,7 +148,15 @@ export default function ActivityDetailsV2(props) {
               </Typography>
             </div>
           </div>
-          <AnchorElemt isLoading={isLoading.delete} onDelete={handleDelete} onEdit={handleEdit} />
+          {props.auth.tags.includes('staff') && (
```
Comment (coderatomy) [inline zubhub_frontend/zubhub/src/views/activity_details/ActivityDetailsV2.jsx]: Only staff users can see the `edit`, `delete`, and `publish/unpublish`

File: zubhub_frontend/zubhub/src/views/my_activities/MyActivities.jsx [hunk 27]
```diff
@@ -0,0 +1,111 @@
...
+                  key={`activityContainer-${index}`}
+                  item
+                  xs={12}
+                  sm={6}
+                  lg={4}
+                  align="center"
+                  className={classes.activityBoxContainer}
+                >
+                  <Activity
+                    key={`activity-${index}`}
```
Comment (brrkrmn) [inline zubhub_frontend/zubhub/src/views/my_activities/MyActivities.jsx:68]: have you considered using activity id instead of index

File: zubhub_frontend/zubhub/src/views/my_activities/MyActivities.jsx [hunk 28]
```diff
@@ -0,0 +1,111 @@
...
+  if (loading) {
+    return <LoadingPage />;
+  } else {
+    if (!activityList || activityList.length === 0) {
+      return <ErrorPage error={props.t('activities.errors.emptyList')} />;
+    } else {
+      return (
+        <div className={commonClasses.smallScreenPadding}>
+          <Typography style={{ marginBottom: 50 }} className={commonClasses.title1}>
+            My Activities
```
Comment (brrkrmn) [inline zubhub_frontend/zubhub/src/views/my_activities/MyActivities.jsx:53]: just a little text to be translated

File: zubhub_frontend/zubhub/src/views/create_activity/step2/Step2.jsx [hunk 29]
```diff
@@ -13,6 +13,7 @@ const idPrefix = 'activitystep';
 const DEFAULT_STEP = { description: '', images: [], title: '', id: uniqueId(idPrefix) };
 
 export default function Step2({ formik, id }) {
+  console.log(formik, 'FORMRMRMR')
```
Comment (brrkrmn) [inline zubhub_frontend/zubhub/src/views/create_activity/step2/Step2.jsx]: i think you forgot this

File: zubhub_frontend/zubhub/src/components/activity/activity.jsx [hunk 30]
```diff
@@ -67,14 +60,7 @@ function Activity(props) {
...
                 ? activity.tags.slice(0, 3).map(tag => (
-                    <Typography
-                      className={
-                        common_classes.baseTagStyle +
-                        ' ' +
-                        classes.activityTagPill
-                      }
-                      key={tag.id}
-                    >
+                    <Typography className={common_classes.baseTagStyle + ' ' + classes.activityTagPill} key={tag.id}>
```
Comment (brrkrmn) [inline zubhub_frontend/zubhub/src/components/activity/activity.jsx:63]: this can also be done with `className={clsx(common_classes.baseTagStyle, classes.activityTagPill)}`

File: zubhub_frontend/zubhub/src/components/activity/activity.jsx [hunk 31]
```diff
@@ -86,11 +72,7 @@ function Activity(props) {
                   onMouseOut={() => setTagsShowMore(false)}
                 >
                   <Typography
-                    className={
-                      common_classes.baseTagStyle +
-                      ' ' +
-                      classes.activityTagsShowMore
-                    }
+                    className={common_classes.baseTagStyle + ' ' + classes.activityTagsShowMore}
```
Comment (brrkrmn) [inline zubhub_frontend/zubhub/src/components/activity/activity.jsx:75]: same here

File: zubhub_frontend/zubhub/src/views/activity_details/ActivityDetailsV2.jsx (hunk 26 above)
Comment (tuxology) [reply zubhub_frontend/zubhub/src/views/activity_details/ActivityDetailsV2.jsx]: Activity creators should be able to see edit and delete as well

**Review by tuxology — APPROVED** [review]
@coderatomy Just https://github.com/unstructuredstudio/zubhub/pull/885#discussion_r1367418866 and resolve conflicts. After this, only the activity cards UX will be left. That needs designer input anyways

**Review by tuxology — CHANGES_REQUESTED** [review]
Switching back to request changes so I don't accidentally merge.

**Comment by coderatomy** [comment]
Conflicts resolved

**Review by tuxology — APPROVED** [review]

File: zubhub_frontend/zubhub/src/views/activity_details/ActivityDetailsV2.jsx (hunk 26 above)
Comment (coderatomy) [reply zubhub_frontend/zubhub/src/views/activity_details/ActivityDetailsV2.jsx]: You mean the one with `creator` tag?

File: zubhub_frontend/zubhub/src/components/Sidenav/data.js [hunk 32]
```diff
@@ -17,7 +17,7 @@ export const links = ({ draftCount, myProjectCount, auth, t }) => [
     { label: t('pageWrapper.sidebar.projects'), link: '/', icon: Dashboard },
     { label: t('pageWrapper.sidebar.profile'), link: '/profile', icon: Person, reactIcon: true, requireAuth: true },
     { label: t('pageWrapper.sidebar.createProject'), link: '/projects/create', icon: EmojiObjects },
-    ...(auth?.tags.includes('staff')
+    ...(['staff', 'creator'].some(tag => auth?.tags.includes(tag))
```
Comment (coderatomy) [inline zubhub_frontend/zubhub/src/components/Sidenav/data.js]: creators can see the `Create Activity` link in the SideNav

Comment (tuxology) [reply zubhub_frontend/zubhub/src/components/Sidenav/data.js]: @coderatomy Can we revert this? We don't want creators to see create activities for now. Only "staff" and "educator" tags can create activities

Comment (coderatomy) [reply zubhub_frontend/zubhub/src/components/Sidenav/data.js]: I was referring from your comment here. It kind of confused things here. https://github.com/unstructuredstudio/zubhub/pull/885#discussion_r1367418866

Comment (coderatomy) [reply zubhub_frontend/zubhub/src/components/Sidenav/data.js]: I think let me just add the `educator` here too?

File: zubhub_frontend/zubhub/src/views/activity_details/ActivityDetailsV2.jsx (hunk 26 above)
Comment (tuxology) [reply zubhub_frontend/zubhub/src/views/activity_details/ActivityDetailsV2.jsx]: The user who created the activity (which is staff and educator tags for now) should be able to edit and delete and activity from the small dropdown menu. Does that clarify this @coderatomy ?

File: zubhub_frontend/zubhub/src/components/Sidenav/data.js (hunk 32 above)
Comment (tuxology) [reply zubhub_frontend/zubhub/src/components/Sidenav/data.js]: Yes, we can add `educator` tag. Only staff and educator roles can create activities for now and hence only they should be able to see "Create Activity" link in sidenav. Added some more clarification here: https://github.com/unstructuredstudio/zubhub/pull/885#discussion_r1372012535

File: zubhub_frontend/zubhub/src/App.js (hunk 19 above)
Comment (tuxology) [reply zubhub_frontend/zubhub/src/App.js:456]: What is this `editting`?

**Review by tuxology — CHANGES_REQUESTED** [review]
A few more comments.

File: zubhub_frontend/zubhub/src/App.js (hunk 19 above)
Comment (coderatomy) [reply zubhub_frontend/zubhub/src/App.js:456]: I talked about it [here](https://github.com/unstructuredstudio/zubhub/pull/885#discussion_r1357710524). Since am using the same component, `CreateEditActivity`, when creating and editting an activity, I needed a way to switch between different label texts, titles, button text and also functionalities. 
Since editing only happens on the `/activity/:id/edit` route, I passed this boolean.

We can use the `url` with help of some regex, but thought this way is more precise and easier

File: zubhub_frontend/zubhub/src/views/activity_details/ActivityDetailsV2.jsx (hunk 26 above)
Comment (coderatomy) [reply zubhub_frontend/zubhub/src/views/activity_details/ActivityDetailsV2.jsx]: Resolved. Thanks

File: zubhub_frontend/zubhub/src/components/Sidenav/data.js (hunk 32 above)
Comment (coderatomy) [reply zubhub_frontend/zubhub/src/components/Sidenav/data.js]: Done

**Comment by coderatomy** [comment]
[Screencast from 2023-10-26 16-53-47.webm](https://github.com/unstructuredstudio/zubhub/assets/141822315/9728a938-2df6-4bb1-95b0-4204f28a682c)

File: zubhub_frontend/zubhub/src/App.js (hunk 19 above)
Comment (tuxology) [reply zubhub_frontend/zubhub/src/App.js:456]: Ok, got it. Maybe we should do something about the typo, but fine for now 🤷

**Review by tuxology — APPROVED** [review]
