### PR TITLE
improveConsistency: fixed title text small, extra vertical space ...

### LINKED ISSUE #210: Consistency of Modal UI elements on mobile
### Issue

UI elements on a modal on mobile are a bit inconsistent:

- [ ] Title Text is small. It seems not to be a title
- [ ] There is extra vertical space between title text and content text
- [ ] Inconsistent padding in buttons. padding of buttons in relation to modal border should be same as top and left padding of title. 

image

### PR DESCRIPTION
**Pull request by Jumeb**
1. Fixed title text too small
2. removed vertical space between title and content text
3. made consistent the padding of buttons to be same as that of the title

Screenshot from 2022-04-02 19-28-18

fixes #210

### CODE REVIEW

**Comment by kamthamc** [comment]
LGTM @tuxology

File: zubhub_frontend/zubhub/src/views/project_details/ProjectDetails.jsx [hunk 1]
```diff
@@ -491,9 +491,11 @@ function ProjectDetails(props) {
           aria-labelledby={t('projectDetails.ariaLabels.deleteProject')}
         >
           <DialogTitle id="delete-project">
+            <Typography variant="h4">
             {t('projectDetails.project.delete.dialog.primary')}
+            </Typography>
           </DialogTitle>
-          <Box
+          {delete_project_dialog_error !== null &&<Box
```
Comment (NdibeRaymond) [inline zubhub_frontend/zubhub/src/views/project_details/ProjectDetails.jsx:498]: `{delete_project_dialog_error !== null &&` shouldn't be here

**Review by NdibeRaymond — CHANGES_REQUESTED** [review]

File: zubhub_frontend/zubhub/src/views/project_details/ProjectDetails.jsx [hunk 2]
```diff
@@ -502,13 +504,13 @@ function ProjectDetails(props) {
                 {delete_project_dialog_error}
               </Box>
             )}
-          </Box>{' '}
+          </Box>}
           <DialogContent>
-            <Typography>
+            <Typography variant="subtitle1">
```
Comment (NdibeRaymond) [inline zubhub_frontend/zubhub/src/views/project_details/ProjectDetails.jsx]: variant="subtitle1" doesn't seem to do much, perhaps remove it?

File: zubhub_frontend/zubhub/src/views/project_details/ProjectDetails.jsx [hunk 3]
```diff
@@ -491,9 +491,11 @@ function ProjectDetails(props) {
...
         >
           <DialogTitle id="delete-project">
+            <Typography variant="h4">
             {t('projectDetails.project.delete.dialog.primary')}
+            </Typography>
           </DialogTitle>
-          <Box
+          {delete_project_dialog_error !== null &&<Box
             component="p"
             className={delete_project_dialog_error !== null && classes.errorBox}
```
Comment (NdibeRaymond) [inline zubhub_frontend/zubhub/src/views/project_details/ProjectDetails.jsx]: since `delete_project_dialog_error !== null &&` was moved so we can conditionally remove the <Box/> component when there is no error, it serves no other purpose here. It makes sense to remove it.

**Review by NdibeRaymond — CHANGES_REQUESTED** [review]

**Comment by Jumeb** [comment]
@NdibeRaymond I have implemented the changes you requested. Please could you review it.

**Review by NdibeRaymond — APPROVED** [review]

**Comment by NdibeRaymond** [comment]
merging this now @Jumeb . Next time if you can, squash your commits into especially when making minor changes. It doesn't hurt here, but it's not exactly a good practice.
