### PR TITLE
Fix login, signup button and nav bar scaling 

### LINKED ISSUE #631: Login and Sign Up do not get scaled along with the entire page
## The bug

If you scale the browser, all the components except the `Login` and `Sign Up` gets scaled along with the page.
If you zoom out up to 50%, the nav bar component ends at a space.

## To Reproduce

- Visit zubhub
- Zoom out from you page and then zoom in

## Expected behavior

Login and sign up button should scale along with the entire website

## Screenshots

On 100%
image

On 75%
image

On 50%
image

Nav bar ending

image

### PR DESCRIPTION
**Pull request by darechan**
## Summary

The `Login` and `Sign Up` gets scaled along with the page and the nav bar doesn't end on completely zooming out and stays consistent with the page

Closes #631 

## Screenshot

On 100% 
image

On 75%
image

On 50%
image

### CODE REVIEW

File: zubhub_frontend/zubhub/src/views/PageWrapper.jsx [hunk 1]
```diff
@@ -279,7 +279,14 @@ function PageWrapper(props) {
                 onSubmit={handleSubmit}
                 ref={formRef}
               >
-                <FormControl className={clsx(common_classes.width100Percent, common_classes.displayFlex, common_classes.displayInlineFlex)} variant="outlined">
+                <FormControl
```
Comment (tuxology) [inline zubhub_frontend/zubhub/src/views/PageWrapper.jsx:282]: All the changes in this file are linter changes am I right?

File: zubhub_frontend/zubhub/src/assets/js/styles/views/page_wrapper/pageWrapperStyles.js [hunk 2]
```diff
@@ -10,7 +10,7 @@ const styles = theme => ({
     fontSize: '1.15rem',
   },
   mainContainerStyle: {
-    maxWidth: '2000px',
+    maxWidth: '6000px',
```
Comment (tuxology) [inline zubhub_frontend/zubhub/src/assets/js/styles/views/page_wrapper/pageWrapperStyles.js]: This seems to me is the only required change

**Review by tuxology — APPROVED** [review]
Clarify comments and then we merge. Update commit messages to explain that linting changes have been made

File: zubhub_frontend/zubhub/src/assets/js/styles/views/page_wrapper/pageWrapperStyles.js (hunk 2 above)
Comment (darechan) [reply zubhub_frontend/zubhub/src/assets/js/styles/views/page_wrapper/pageWrapperStyles.js]: Yes it was needed so that it could fit all the screen sizes

File: zubhub_frontend/zubhub/src/views/PageWrapper.jsx (hunk 1 above)
Comment (darechan) [reply zubhub_frontend/zubhub/src/views/PageWrapper.jsx:282]: yes they are linter changes that got made by the `prettier` extension I use so that the code runs error free like adding semicolon at the end just for good practice and writing each attribute on a next line to make it look neat. I can reverse them if there is an issue.

Comment (darechan) [reply zubhub_frontend/zubhub/src/views/PageWrapper.jsx:282]: I'll keep in mind to turn it off the next time I make any change.

File: zubhub_frontend/zubhub/src/views/PageWrapper.jsx [hunk 3]
```diff
@@ -390,7 +397,7 @@ function PageWrapper(props) {
                       variant="outlined"
                       size="large"
                       secondaryButtonStyle
-                      customButtonStyle
+                      className={classes.customButton}
```
Comment (darechan) [inline zubhub_frontend/zubhub/src/views/PageWrapper.jsx:400]: This change was needed for the button to scale along with the nav bar

File: zubhub_frontend/zubhub/src/views/PageWrapper.jsx (hunk 1 above)
Comment (tuxology) [reply zubhub_frontend/zubhub/src/views/PageWrapper.jsx:282]: It's ok, we should keep it turned on 👍

Comment (darechan) [reply zubhub_frontend/zubhub/src/views/PageWrapper.jsx:282]: Cool I hope it can be merged then!

File: zubhub_frontend/zubhub/src/views/PageWrapper.jsx [hunk 4]
```diff
@@ -407,7 +414,7 @@ function PageWrapper(props) {
                       size="large"
                       primaryButtonStyle
                       customButtonStyle
-                      className={common_classes.marginLeft1em}
+                      className={`${common_classes.marginLeft1em} ${classes.customButton}`}
```
Comment (chaitanya-cloudknox) [inline zubhub_frontend/zubhub/src/views/PageWrapper.jsx:417]: use `clsx`

File: zubhub_frontend/zubhub/src/views/PageWrapper.jsx [hunk 5]
```diff
@@ -617,39 +624,39 @@ function PageWrapper(props) {
                     {props.auth.tags.filter(
                       tag => tag === 'staff' || tag === 'educator',
                     ).length > 0 && (
-                        <MenuItem
-                          className={clsx(common_classes.removeOnSmallScreen)}
-                          onClick={() => {
-                            history.push('/activities', { flag: 'educator' });
-                          }}
+                      <MenuItem
```
Comment (chaitanya-cloudknox) [inline zubhub_frontend/zubhub/src/views/PageWrapper.jsx:627]: For URLs Its better to use anchor tags instead of using MenuItem for accessibility reasons and you will miss some options like open in a new tab etc.

File: zubhub_frontend/zubhub/src/assets/js/styles/views/page_wrapper/pageWrapperStyles.js (hunk 2 above)
Comment (chaitanya-cloudknox) [inline zubhub_frontend/zubhub/src/assets/js/styles/views/page_wrapper/pageWrapperStyles.js]: I don't think its a good idea there should be some other issue we need to figure it out

Comment (chaitanya-cloudknox) [reply zubhub_frontend/zubhub/src/assets/js/styles/views/page_wrapper/pageWrapperStyles.js]: can you try `100vw` its 100% width of the device

File: zubhub_frontend/zubhub/src/views/PageWrapper.jsx (hunk 4 above)
Comment (darechan) [reply zubhub_frontend/zubhub/src/views/PageWrapper.jsx:417]: this works just fine?

File: zubhub_frontend/zubhub/src/views/PageWrapper.jsx (hunk 5 above)
Comment (darechan) [reply zubhub_frontend/zubhub/src/views/PageWrapper.jsx:627]: These are just linter changes not refactor changes

**Review by tuxology — APPROVED** [review]
