### PR TITLE
Fix: Miscellanous changes to keep header and hero style consistent

### LINKED ISSUE #934: Miscellaneous issues introduced via header and navbar changes
After recent merges and changes to the navbar and hero elements via https://github.com/unstructuredstudio/zubhub/pull/883 and #946  (which we overlooked), we have an alignment issue with the navbar and main hero element in addition to various other issues (button size, font size. avatar color etc)

image 

Following sub-tasks are identified to be fixed:

- [x] The navbar root should not be 100% width - it should be in centre as it was before
- [x] Hero elements should be contained in a container which should follow navbar width and elements inside it should follow consistent responsiveness
- [x] Header does not show image on mobile screen. 
- [x] Heights of Featured Projects heading does not match other headings
- [x] Varied Buttons sizes (particular "login to view more" should be fixed and made uniform)
- [x] Avatar color in non logged-in navbar should be reverted back to what it was before

### PR DESCRIPTION
**Pull request by aqsaaqeel**
## Summary

- The main hero section on the landing page was not showing the image. This was caused because there wasn't a conditional in place for mobile size.
- The `featured projects` section's heading and button on the landing page were not consistent with that of the rest of the sections.
- The navbar width was set to 100% on desktop screens which is not required according to current design.
- The avatar button was blank when not logged in.
- The hero section contents width was not aligned with navbar.

## Screenshots

Image now appearing normally:

Screenshot from 2023-10-21 06-02-47

Featured Projects heading consistent now:

Screenshot from 2023-10-21 06-04-00

Featured Projects buttons style consistent with rest of the buttons:

Screenshot from 2023-10-21 06-04-04

## Concerns after this PR

The featured projects section is rendered as a whole component. This component is also used on the dashboard. Changing the heading style changes it on the dashboard too. Is this alright? 

Screenshot from 2023-10-21 06-09-40

### CODE REVIEW

**Comment by srish** [comment]
Closing as a duplicate of https://github.com/unstructuredstudio/zubhub/issues/934

**Comment by aqsaaqeel** [comment]
> Closing as a duplicate of #934

hey @srish this is a PR I raised to fix #934 🤔 why was this closed?

**Comment by tuxology** [comment]
@aqsaaqeel Please see the updated scope on ticket #934. Update the PR description and title as well on this. Reopening this.

**Comment by aqsaaqeel** [comment]
> @aqsaaqeel Please see the updated scope on ticket #934. Update the PR description and title as well on this. Reopening this.

Thanks, on it!

**Comment by tuxology** [comment]
@aqsaaqeel Are you working on this? This is important since we need to fix regressions we introduced.

**Comment by aqsaaqeel** [comment]
> @aqsaaqeel Are you working on this? This is important since we need to fix regressions we introduced.

I've made the changes, my concern is the hero section layout. The new Figma design was suitable for 100% width. For now, I have added multiple breakdowns to make it responsive (so it is easier to revert any changes if required)

**Comment by aqsaaqeel** [comment]
Regression issue fixed with this PR

1. Hero section image on mobile screens

Screenshot from 2023-10-28 12-05-29

2. Navbar width for its content reverted to its initial state

Screenshot from 2023-10-28 12-08-24

3.  Hero Section container to be consistent with navbar contents.

Screenshot from 2023-10-28 11-31-33

4. Avatar icon to show default avatar when unauthenticated.

Screenshot from 2023-10-28 12-08-24

when authenticated:

Screenshot from 2023-10-28 12-11-38

5. Heading and buttons for featured projects to be consistent with the rest of the headings and buttons on the landing page.

Screenshot from 2023-10-28 11-32-57

**Comment by aqsaaqeel** [comment]
@kamthamc @tuxology This is ready for review

File: zubhub_frontend/zubhub/src/assets/js/styles/components/staff_pick/staffPickStyles.js [hunk 1]
```diff
@@ -13,6 +13,10 @@ const styles = theme => ({
   projectGridStyle: {
     marginBottom: '2em',
   },
+  MessagePrimaryStyle: {
+    fontSize: '2.5rem',
+    fontWeight: 1000,
```
Comment (kamthamc) [inline zubhub_frontend/zubhub/src/assets/js/styles/components/staff_pick/staffPickStyles.js:18]: it shouldn't be 1000 🤔

File: zubhub_frontend/zubhub/src/components/avatar_button/AvatarButton.jsx [hunk 2]
```diff
@@ -23,25 +23,35 @@ const AvatarButton = props => {
...
       <div>
-        <Avatar
-          ref={buttonRef}
-          onClick={onClickSignUp}
-          className={commonClasses.iconBox}
-          alt={auth?.username?.toUpperCase()}
-          src={auth?.avatar}
-        />
+        {!auth.token ? (
+          <Avatar
```
Comment (kamthamc) [inline zubhub_frontend/zubhub/src/components/avatar_button/AvatarButton.jsx:38]: the usage looks same. may be just change props if token is available

File: zubhub_frontend/zubhub/src/views/home/Home.jsx [hunk 3]
```diff
@@ -161,8 +161,8 @@ function Projects(props) {
                      <Box className={classes.heroImageContainerStyle}>
                        <img
                          className={classes.heroImageStyle}
-                         src={hero.image_url}
-                         alt=""
+                         src={hero.image_url ? hero.image_url : heroMainImage}
+                         alt="Six animated children happily walking"
```
Comment (kamthamc) [inline zubhub_frontend/zubhub/src/views/home/Home.jsx]: it needs to be translated

File: zubhub_frontend/zubhub/src/assets/js/styles/components/staff_pick/staffPickStyles.js (hunk 1 above)
Comment (aqsaaqeel) [reply zubhub_frontend/zubhub/src/assets/js/styles/components/staff_pick/staffPickStyles.js:18]: Since the aim was to make the heading for the Featured Project section the same as the headings on other sections on the landing page, I have used the same style used in those headings.

File: zubhub_frontend/zubhub/src/components/avatar_button/AvatarButton.jsx (hunk 2 above)
Comment (aqsaaqeel) [reply zubhub_frontend/zubhub/src/components/avatar_button/AvatarButton.jsx:38]: Thank you for the review, I have refactored the code.

File: zubhub_frontend/zubhub/src/assets/js/styles/components/staff_pick/staffPickStyles.js (hunk 1 above)
Comment (chaitanya-cloudknox) [reply zubhub_frontend/zubhub/src/assets/js/styles/components/staff_pick/staffPickStyles.js:18]: Sorry my mistake was thinking of some other property which should be <10

File: zubhub_frontend/zubhub/src/assets/js/styles/views/projects/projectsStyles.js [hunk 4]
```diff
@@ -25,21 +25,32 @@ const styles = theme => ({
...
+    padding: '0 16.5em',
+    paddingTop: '2em',
+    paddingBottom: '2em',
     justifyContent: 'center',
-    width: '100vw',
+    // width: '100%',
+    // maxWidth: '1230px',
     marginBottom: '2em',
     height:'100vh',
+    [theme.breakpoints.down('1620')]: {
```
Comment (tuxology) [inline zubhub_frontend/zubhub/src/assets/js/styles/views/projects/projectsStyles.js]: I don't feel adding 3 extra breakpoints - two of which are very close and very arbitrary is the correct way to solve this. Breakpoints should remain fixed and within them, the hero elements can size relatively.  For example. explore use of `em` for font sizing and for padding, there is some other underlying issue that padding is not adjusting on existing breakpoints. I am sure there is a much cleaner way to do this

**Review by tuxology — CHANGES_REQUESTED** [review]
We still need to figure out a way to address the hero element issue properly. We may not need many breakpoitns if the padding/font sizing is handled properly.  We do need this change sooner than later.

**Comment by aqsaaqeel** [comment]
Can I deviate from the figma design a bit and test with smaller font size to accommodate the padding?

**Comment by aqsaaqeel** [comment]
@tuxology I have now used calc for taking care of padding and the layout looks responsive, please review

**Review by tuxology — APPROVED** [review]
OK, this LGTM for now - much cleaner as well. Lets merge and see if there are improvements 👍
