### PR TITLE
fix: header styles and heading of projects

### LINKED ISSUE #792: Improve the header design on the landing page
Review@2x

1. The Hero Text lacks Hierarchy and the CTA button isn't bold enough to call attention to the user. 
2. The logo and hero text are not aligned vertically
3. The Creator Review section has a visibility issue. The text color and background color do not pass the contrast check.

### PR DESCRIPTION
**Pull request by aqsaaqeel**
## Summary

-> Used the finalized design in https://github.com/unstructuredstudio/zubhub/issues/792 to develop the hero section. 

-> The hero table is not populated so the image needs to be added from the backend. 

-> To run it and test, I added the Hero details on [http://localhost:8000/admin](https://github.com/unstructuredstudio/zubhub/pull/url)

-> As for this PR, I have made all the necessary CSS changes and added the necessary components.

## Changes

- Hero Container design on landing page
- Translated title for both English and Hindi
- Font Size of the heading Featured Project to match the rest

## Screenshots
I have made the changes according to @srish instructions [here](https://github.com/unstructuredstudio/zubhub/issues/792#issuecomment-1756589431)
Screenshot from 2023-10-12 18-43-00

### CODE REVIEW

**Comment by aqsaaqeel** [comment]
I have made the changes you suggested @tuxology SInce the hero section text had a different style than the rest of the titles, they needed new classes for styles to be made. Here is how the hero section looks now.
Screenshot from 2023-10-13 10-44-13
Screenshot from 2023-10-13 10-43-38

File: zubhub_frontend/zubhub/src/views/home/Home.jsx [hunk 1]
```diff
@@ -103,8 +102,8 @@ function Projects(props) {
           (
             <Box className={classes.root}>
               {hero && hero.id ? (
-                 <Box className={classes.heroSectionStyle}>
-                 <Box className={classes.heroContainerStyle}>
+                 <Box className={classes.heroMainSectionStyle}>
```
Comment (tuxology) [inline zubhub_frontend/zubhub/src/views/home/Home.jsx:105]: Why have we renamed it to `heroMainSection` style instead of old name?

**Review by tuxology — CHANGES_REQUESTED** [review]
Few changes we need: 
 - [ ]  The UI does not match the design in terms of width of hero element. It is currently full width however in the proposed design, we need to align it in the same width as the container containing elements of navbar. 
 -  [ ] In mobile view, there needs to be padding between Share your Work button and the image and the image needs to be center aligned

File: zubhub_frontend/zubhub/src/views/home/Home.jsx (hunk 1 above)
Comment (aqsaaqeel) [reply zubhub_frontend/zubhub/src/views/home/Home.jsx:105]: There is another section on this page that uses the ```heroSectionStyle``` name for its classes. It is the carousel section for ambassadors and their testimonials. 
Making any changes to the already existing classes meant changing other sections as collateral too. However, since we were focusing on just the Hero Section and it required different styling than the rest of the components, I made a new class.

**Comment by aqsaaqeel** [comment]
> Few changes we need:
> 
> * [ ]   The UI does not match the design in terms of width of hero element. It is currently full width however in the proposed design, we need to align it in the same width as the container containing elements of navbar.
> * [ ]  In mobile view, there needs to be padding between Share your Work button and the image and the image needs to be center aligned

Changes I have made in this commit:
- The padding for `navbar` is adjusted.
- Padding space between `hero button` and `hero image` has been added.

Screenshot from 2023-10-14 05-54-03
As for the image on mobile screen, it looks centered here, is this what you meant? @tuxology 
Screenshot from 2023-10-14 05-51-56


Since the scope of this PR is just the hero section, I haven't altered much on the navbar, but I feel like we should also implement the design for the icons from [this](https://www.figma.com/file/nyUduEpFmVZ05xA8rt28Mt/ZubHub-Feature-Re-Designs?type=design&node-id=11-414&mode=design&t=xDeX7LSKbik6YPFy-0)

File: zubhub_frontend/zubhub/src/assets/js/styles/views/projects/projectsStyles.js [hunk 2]
```diff
@@ -108,20 +137,44 @@ const styles = theme => ({
...
     textTransform: 'none',
-    padding: '0 1em',
-    fontSize: '1.2rem',
+    fontSize: '1.456rem',
     fontWeight: 700,
     marginRight: '1em',
     marginTop: '1.2em',
+    width: 'fit-content',
+    height: '3.95rem',
+    padding: '1.04rem 2.08rem 1.04rem 2.08rem',
```
Comment (tuxology) [inline zubhub_frontend/zubhub/src/assets/js/styles/views/projects/projectsStyles.js]: So there are two decimal places here. Why do we need such accuracy?

File: zubhub_frontend/zubhub/src/assets/js/styles/views/projects/projectsStyles.js [hunk 3]
```diff
@@ -108,20 +137,44 @@ const styles = theme => ({
...
+    fontWeight: 500,
+    [theme.breakpoints.down('sm')]: {
+      fontSize: '1.2rem'
+    },
+  },
   heroButtonStyle: {
     textTransform: 'none',
-    padding: '0 1em',
-    fontSize: '1.2rem',
+    fontSize: '1.456rem',
```
Comment (tuxology) [inline zubhub_frontend/zubhub/src/assets/js/styles/views/projects/projectsStyles.js]: Why do we need 3 decimal accurate values? How have these been calculated? I feel if we need such fine adjustments, then there must be some underlying issue

**Review by tuxology — APPROVED** [review]
I am fine with this, but need a few clarifications/modifications on comments before we merge @aqsaaqeel

File: zubhub_frontend/zubhub/src/assets/js/styles/views/projects/projectsStyles.js (hunk 2 above)
Comment (aqsaaqeel) [reply zubhub_frontend/zubhub/src/assets/js/styles/views/projects/projectsStyles.js]: I use the Figma design to show me the exact styles applied, and those are in `px`. I convert them to `rem` because it is more flexible in terms of adjusting according to screen sizes. The `px` values are a whole number but converting them to `rem` gives these decimal values.

File: zubhub_frontend/zubhub/src/assets/js/styles/views/projects/projectsStyles.js (hunk 3 above)
Comment (aqsaaqeel) [reply zubhub_frontend/zubhub/src/assets/js/styles/views/projects/projectsStyles.js]: No, I don't think there is any underlying issue. My reasoning is the same as above ☝️

File: zubhub_frontend/zubhub/src/assets/js/styles/views/projects/projectsStyles.js (hunk 2 above)
Comment (tuxology) [reply zubhub_frontend/zubhub/src/assets/js/styles/views/projects/projectsStyles.js]: @aqsaaqeel Can we round the double digit values to single digit at the very minimum? You can eyeball them to see if they align. Usually, there should be minimum need to do such "fine tuning". The figma designs are not supposed to be accurate representations to the exact location, but just indication of how things are aligned. Another benefit of keeping simple numbers is that we don't have to do a lot of fine tuning in other places (containers/padding) - since they will also align to single values.

Comment (aqsaaqeel) [reply zubhub_frontend/zubhub/src/assets/js/styles/views/projects/projectsStyles.js]: Alright. I'll make the changes!

**Comment by tuxology** [comment]
@aqsaaqeel Can you revert navbar height? We don't want to change it yet

**Review by tuxology — CHANGES_REQUESTED** [review]
See comment about navbar height.

**Comment by aqsaaqeel** [comment]
> See comment about navbar height.

Alright! Can I work on #801 too on this PR? @tuxology

**Review by tuxology — APPROVED** [review]

**Comment by tuxology** [comment]
@aqsaaqeel Lets leave #801 for now.

Also, sorry for increasing the scope of this PR, but can we actually harcode the header SVG here in the code itself? (add the  SVG to the PR and use it). We can keep the custom image upload feature (which is currently in Django Admin) still. We can add a checkbox in the Django Admin to select default image to be used OR uploaded image. Is that doable?

**Comment by aqsaaqeel** [comment]
> We can add a checkbox in the Django Admin to select default image to be used OR uploaded image

It's alright. I'm on it!

**Comment by aqsaaqeel** [comment]
@tuxology I've added the svg image but I am not able to understand why we need the optional image on admin. We are controlling what goes in the header image in the frontend anyway. So wouldn't the choice of which image we want to display come from the frontend even if we want to put the image from Admin? 🤔

File: zubhub_frontend/zubhub/src/assets/js/styles/views/projects/projectsStyles.js [hunk 4]
```diff
@@ -25,20 +25,35 @@ const styles = theme => ({
...
   },
-  heroSectionStyle: {
+  heroMainSectionStyle: {
     backgroundColor: 'var(--primary-color1)',
-    boxShadow: '-2px 25px 13px -18px rgba(220,53,69,0.7)',
-    WebkitBoxShadow: '-2px 25px 13px -18px rgba(220,53,69,0.7)',
-    MozBoxShadow: '-2px 25px 13px -18px rgba(220,53,69,0.7)',
     display: 'flex',
     paddingTop: '2.3em',
     paddingBottom: '2.85em',
```
Comment (tuxology) [inline zubhub_frontend/zubhub/src/assets/js/styles/views/projects/projectsStyles.js]: Can you do rounding?

File: zubhub_frontend/zubhub/src/assets/js/styles/views/projects/projectsStyles.js [hunk 5]
```diff
@@ -99,6 +127,7 @@ const styles = theme => ({
   heroMessageContainerStyle: {
     flexGrow: 1,
     color: 'white',
+    maxWidth: '37.813rem',
```
Comment (tuxology) [inline zubhub_frontend/zubhub/src/assets/js/styles/views/projects/projectsStyles.js]: Rounding

File: zubhub_frontend/zubhub/src/assets/js/styles/views/projects/projectsStyles.js [hunk 6]
```diff
@@ -108,20 +137,44 @@ const styles = theme => ({
...
   heroButtonStyle: {
     textTransform: 'none',
-    padding: '0 1em',
-    fontSize: '1.2rem',
+    fontSize: '1.456rem',
     fontWeight: 700,
     marginRight: '1em',
     marginTop: '1.2em',
+    width: 'fit-content',
+    height: '3.95rem',
```
Comment (tuxology) [inline zubhub_frontend/zubhub/src/assets/js/styles/views/projects/projectsStyles.js]: Rounding

**Review by tuxology — CHANGES_REQUESTED** [review]
Please review the code again for decimal rounding suggestions. Eyeball the UI once you have rounded the values.

**Comment by tuxology** [comment]
> @tuxology I've added the svg image but I am not able to understand why we need the optional image on admin. We are controlling what goes in the header image in the frontend anyway. So wouldn't the choice of which image we want to display come from the frontend even if we want to put the image from Admin? 🤔

The idea for user provided hero element was to make the image modifiable from time to time (eg. highlight some news, upcoming event etc). The flow is this:
 - Default image is one hardcoded in frontend. In absence of any header image upload from Django Admin, this is what is shown
 - If custom image is uploaded AND the checkbox ticked, then the custom image takes precedence in rendering. 
 - If custom image is uploaded but the checkbox is not ticked, default image will be used

This flow can be coded in the frontend to get this working.

**Comment by aqsaaqeel** [comment]
> > @tuxology I've added the svg image but I am not able to understand why we need the optional image on admin. We are controlling what goes in the header image in the frontend anyway. So wouldn't the choice of which image we want to display come from the frontend even if we want to put the image from Admin? 🤔
> 
> The idea for user provided hero element was to make the image modifiable from time to time (eg. highlight some news, upcoming event etc). The flow is this:
> 
> * Default image is one hardcoded in frontend. In absence of any header image upload from Django Admin, this is what is shown
> * If custom image is uploaded AND the checkbox ticked, then the custom image takes precedence in rendering.
> * If custom image is uploaded but the checkbox is not ticked, default image will be used
> 
> This flow can be coded in the frontend to get this working.

I have added the conditional to render the hardcoded image if there isn't one coming from the admin already.
As per the use case which you have mentioned, when we want a modified image, we can:
-> Go to admin panel.
-> Upload custom image.
After the said event expires, we can remove the custom image.
-> To clear it, there's already a clear selection box given. We can clear, save changes. And refresh.

Untitled design (1)



Do we have to add a checkbox on top of this ☝️
 
There is another issue that we can see now. The image coming from the admin works properly but the concern is the design does not have padding on the right as we can see here. (this is not an issue for the hardcoded image because of how it is designed) Should I work on this?

Screenshot from 2023-10-20 00-23-55

**Comment by tuxology** [comment]
I think this is fine for now 👍 We can iteratively improve it further

**Review by tuxology — APPROVED** [review]
LGTM 🌈
