### PR TITLE
fix: labelWidth removed

### LINKED ISSUE #181: Unable to create a project with no or any tag
The error below shows up when you try to create a project with no or any tag: 
WhatsApp Image 2021-06-07 at 8 59 10 AM

Also, the child user with whom I did the testing says he is not able to understand what to enter in this field. We should either remove this field or explain here what tag means or give an example of a tag

### PR DESCRIPTION
**Pull request by aqsaaqeel**
## Summary

labelWidth was undefined
Closes #181

Fixes the error in https://github.com/unstructuredstudio/zubhub/pull/745 @tuxology

### CODE REVIEW

File: zubhub_frontend/zubhub/src/views/edit_profile/EditProfile.jsx [hunk 1]
```diff
@@ -558,7 +558,7 @@ function EditProfile(props) {
                   ref={username_check}
                   name="username"
                   type="text"
-                  labelWidth={calculateLabelWidth(t('profile.delete.dialog.inputs.username.label'), document)}
+                  label={t('editProfile.inputs.email.label')}
```
Comment (brrkrmn) [inline zubhub_frontend/zubhub/src/views/edit_profile/EditProfile.jsx]: can you change the t function parameter with this:

'profile.delete.dialog.inputs.username.label'

File: zubhub_frontend/zubhub/src/views/edit_profile/EditProfile.jsx [hunk 2]
```diff
@@ -602,7 +602,7 @@ function EditProfile(props) {
                       </IconButton>
                     </InputAdornment>
                   }
-                  labelWidth={calculateLabelWidth(t('profile.delete.dialog.inputs.password.label'), document)}
+                  label={t('editProfile.inputs.email.label')}
```
Comment (brrkrmn) [inline zubhub_frontend/zubhub/src/views/edit_profile/EditProfile.jsx]: can you change t function parameter with this: 

'profile.delete.dialog.inputs.password.label'

**Review by brrkrmn — APPROVED** [review]
Looks good  🙌🏻

**Review by tuxology — APPROVED** [review]
