### PR TITLE
Fix footer links

### LINKED ISSUE #625: Make Footer links change color on hover
I think it will be better and also intuitive to the users if the links in the footer changed color to say #03848c on hover.

Screenshot (84)

### PR DESCRIPTION
**Pull request by skynette**
## Summary

This PR adds some styling to make the footer links change color on hover. The `footerLinkStyle` class has been updated with the following properties:

```javascript
footerLinkStyle: {
  color: 'white',
  cursor: 'pointer',
  '&:hover': {
    color: 'rgb(254 211 42)',
  },
},

```
This will change the color of the links when the mouse is hovering over them.

Fixes #625

## Changes

-   Updated `footerLinkStyle` class to change link color on hover.
## Screenshots
image

### CODE REVIEW

**Comment by Collins-Omariba** [comment]
@skynette Could you maybe use the  #03848c, color since it will be more different from the background color and also blend in.

**Comment by skynette** [comment]
> 

It looks dull, I thought maybe a color from the website that compliments it looks better

**Comment by Collins-Omariba** [comment]
Ok if it looks dull, It's the bluish color from the website though.

**Comment by skynette** [comment]
@tuxology can you review this PR?

File: zubhub_frontend/zubhub/src/assets/js/styles/views/page_wrapper/pageWrapperStyles.js [hunk 1]
```diff
@@ -259,8 +259,12 @@ const styles = theme => ({
   },
   footerLinkStyle: {
     color: 'white',
-  },
-  center: {
+    cursor: 'pointer',
+    '&:hover': {
+      color: 'rgb(254 211 42)',
```
Comment (tuxology) [inline zubhub_frontend/zubhub/src/assets/js/styles/views/page_wrapper/pageWrapperStyles.js]: Instead of using a primary color (zubhub yellow), can we use something which is a lighter version of ZubHub's red color?

**Review by tuxology — CHANGES_REQUESTED** [review]

File: zubhub_frontend/zubhub/src/assets/js/styles/views/page_wrapper/pageWrapperStyles.js (hunk 1 above)
Comment (skynette) [reply zubhub_frontend/zubhub/src/assets/js/styles/views/page_wrapper/pageWrapperStyles.js]: okay I guess I could make that work

Comment (skynette) [reply zubhub_frontend/zubhub/src/assets/js/styles/views/page_wrapper/pageWrapperStyles.js]: image

will this be suitable?

Comment (tuxology) [reply zubhub_frontend/zubhub/src/assets/js/styles/views/page_wrapper/pageWrapperStyles.js]: Works!

**Comment by skynette** [comment]
@tuxology I have made the requested changes, you can merge it now

**Review by tuxology — APPROVED** [review]
