### PR TITLE
fix: adds a margin to the items

### LINKED ISSUE #866: No horizontal spacing between cards on search results page
**Describe the bug**
Search result for logged in users is not adequately spaced

**To Reproduce**

1. Visit 'Zubhub website'
2. Click on 'Log in and make sure you are logged in'
3. Search for project 'light'

**Expected behavior**
adequate spacing between cards

**Screenshots**
space

### PR DESCRIPTION
**Pull request by yokwejuste**
## Summary

Description of PR here...
Closes #866

## Changes

- The search result files

## Screenshots

image

### CODE REVIEW

**Comment by tuxology** [comment]
Not convinced about this approach. Asking @kamthamc for his views.

File: zubhub_frontend/zubhub/src/views/search_results/SearchResults.jsx [hunk 1]
```diff
@@ -37,7 +37,13 @@ import Project from '../../components/project/Project';
 import styles from '../../assets/js/styles/views/search_results/searchResultsStyles';
 import commonStyles from '../../assets/js/styles';
 
-const useStyles = makeStyles(styles);
+const useStyles = makeStyles({
+  ...styles,
```
Comment (chaitanya-cloudknox) [inline zubhub_frontend/zubhub/src/views/search_results/SearchResults.jsx]: * `styles` is actually a function, spreading shouldn't work. `const styles = theme => ({`
* Instead of duplicating styles, just apply two classnames for the html element.

Comment (yokwejuste) [reply zubhub_frontend/zubhub/src/views/search_results/SearchResults.jsx]: Not understanding, please can you elaborate?

Comment (chaitanya-cloudknox) [reply zubhub_frontend/zubhub/src/views/search_results/SearchResults.jsx]: this file exports a function https://github.com/yokwejuste/zubhub/blob/fix/spacing/zubhub_frontend/zubhub/src/assets/js/styles/views/search_results/searchResultsStyles.js

we can only spread object or an array, the usage of styles is wrong.

Comment (yokwejuste) [reply zubhub_frontend/zubhub/src/views/search_results/SearchResults.jsx]: Great, thanks, will do some research on this

Comment (chaitanya-cloudknox) [reply zubhub_frontend/zubhub/src/views/search_results/SearchResults.jsx]: you could to something like this.

```javascript
const useCommonStyles = makeStyles(theme => ({
  someClassName: {}
}}))
const useSpecificStyles = makeStyles(theme => ({
  someClassName: {},
   two: {}
}}))

const MyComponent = () => {
   const commonClassNames = useCommonStyles();
   const specificClassNames = useSpecificStyles();
   return <div className={cslx(commonClassNames.someClassName, specificClassNames.someClassName, specificClassNames.two)}>text</div>
}
```

This will reduce duplicate css

**Comment by tuxology** [comment]
@yokwejuste Any updates on this?

**Comment by yokwejuste** [comment]
> @yokwejuste Any updates on this?

working on it @tuxology

**Comment by yokwejuste** [comment]
> @yokwejuste Any updates on this?

Some pushes were made sir

> @yokwejuste Any updates on this?

Hey @tuxology  the PR is ready for merge now.

**Review by tuxology — APPROVED** [review]
