### PR TITLE
feat: implements new style for project number and fix lagging

### LINKED ISSUE #912: Fix lag around drafts & projects count and improve design
**Describe the bug**
Creation of project and activities has a draft number lag.
**To Reproduce**
Follow the steps below:

1. Go to zubhub 
2. Login
3. Go to activities creation or project creation and you see the `Saved to draft` when you have not yet started using.
4. See error, drafts are not in sync, keeps lagging

**Expected behavior**
Normally it was to show saved to draft after step one is complete. And on step 2 we were to see the draft incrementing

**Screenshots**
image
image
image

### PR DESCRIPTION
**Pull request by yokwejuste**
## Summary

Description of PR here...
Closes #912

## Changes
- The tag style
- fetch the draft and project values using useEffect

#### Progress
------------------------
image
-----------------------
image image 
-------------------------
imageimage
-------------------------
### Result
image

### CODE REVIEW

**Comment by yokwejuste** [comment]
@mehreeee @srish please kindly have a look at these changes.

cc: @tuxology @coderatomy

**Comment by coderatomy** [comment]
Looks nice. Just a suggestion, I think we shouldn't display anything if there is nothing, i.e instead of showing `0`

**Comment by mehreeee** [comment]
> @mehreeee @srish please kindly have a look at these changes.
> 
> cc: @tuxology @coderatomy

Just seeing this now. Can you remove the zero? Like when there’s no drafts, nothing shows. Secondly the green frame around the number shouldn’t be a fixed width. Only the height is fixed. The width should grow as the numbers increases.

**Comment by yokwejuste** [comment]
> > @mehreeee @srish please kindly have a look at these changes.
> > 
> > cc: @tuxology @coderatomy
> 
> Just seeing this now. Can you remove the zero? Like when there’s no drafts, nothing shows. Secondly the green frame around the number shouldn’t be a fixed width. Only the height is fixed. The width should grow as the numbers increases.

The actual final result was the one with displays for the drafts and projects

**Comment by yokwejuste** [comment]
> Looks nice. Just a suggestion, I think we shouldn't display anything if there is nothing, i.e instead of showing `0`

Got it, I'll put a condition to remove it there

**Comment by yokwejuste** [comment]
@tuxology  @srish @mehreeee 

done here for now

cc: @coderatomy

**Comment by tuxology** [comment]
@kamthamc Can you review this?

File: zubhub_frontend/zubhub/src/components/Sidenav/Sidenav.jsx [hunk 1]
```diff
@@ -35,12 +36,16 @@ export default function Sidenav() {
...
     const request1 = api.getUserDrafts({ username: auth?.username, token: auth?.token });
     const request2 = api.getUserProjects({ username: auth?.username, token: auth?.token });
-    let res = Promise.all([request1, request2]);
-    res.then(data => {
-      setDraftCount(data[0].count);
-      setMyProjectCount(data[1].count);
-    });
-  }, []);
+
+    Promise.all([request1, request2])
```
Comment (kamthamc) [inline zubhub_frontend/zubhub/src/components/Sidenav/Sidenav.jsx:40]: Use allSettled, even if one of them fails we could continue with data from other requests.

Do not use allsettled if the data is dependent on each other

File: zubhub_frontend/zubhub/src/components/Sidenav/Sidenav.jsx [hunk 2]
```diff
@@ -64,24 +69,60 @@ export default function Sidenav() {
...
+                      <ListItemText
+                        primary={
+                          <span>
+                            {label}
+                            <CustomButton
+                              variant="outlined"
+                              customButtonStyle
+                              className={classes.customNumberTag}
+                            >
+                              {label === 'My Drafts' ? (draftCount > 0 ? draftCount : '') : (myProjectCount > 0 ? myProjectCount : '')}
```
Comment (kamthamc) [inline zubhub_frontend/zubhub/src/components/Sidenav/Sidenav.jsx]: Do not use labels for comparison, it might fail in non English languages, instead created id, and also use the id for the key

File: zubhub_frontend/zubhub/src/components/Sidenav/sidenav.styles.js [hunk 3]
```diff
@@ -59,5 +59,25 @@ export const sidenavStyle = theme => ({
     link: {
         textDecoration: 'none', padding: '0 30px',
     },
-    listContainer: { display: 'flex', flex: 1, flexDirection: 'column', paddingTop: 30 }
+    listContainer: { display: 'flex', flex: 1, flexDirection: 'column', paddingTop: 30 },
+    customNumberTag: {
+        backgroundColor: colors.primary,
+        color: 'white !important',
```
Comment (kamthamc) [inline zubhub_frontend/zubhub/src/components/Sidenav/sidenav.styles.js]: Try avoiding !important. Check why you need to do that, try to fix that instead

**Review by tuxology — APPROVED** [review]
LGTM 🌈
